Repository kakao-tech-campus-2nd-step3/Team9_FE, pull requests merged in 2024-10, with the labels that each got.

#19 아이콘 및 로고 svg 파일 추가 #18
  src/assets/.gitkeep
  src/assets/icons/add.svg
  src/assets/icons/arrow-back.svg
  src/assets/icons/arrow-forward.svg
  src/assets/icons/arrow-outward.svg
  src/assets/icons/arrow-upward.svg
  src/assets/icons/cancel-default.svg
  src/assets/icons/cancel-filled.svg
  src/assets/icons/chat-default.svg
  src/assets/icons/chat-filled.svg
  src/assets/icons/check-box-checked.svg
  src/assets/icons/check-box-unchecked.svg
  src/assets/icons/check_circle.svg
  src/assets/icons/close.svg
  src/assets/icons/dashboard-default.svg
  src/assets/icons/dashboard-filled.svg
  src/assets/icons/delete.svg
  src/assets/icons/edit.svg
  src/assets/icons/favorite-default.svg
  src/assets/icons/favorite-filled-black.svg
  src/assets/icons/favorite-filled-red.svg
  src/assets/icons/home-default.svg
  src/assets/icons/home-filled.svg
  src/assets/icons/menu-hamburger.svg
  src/assets/icons/menu-kebab.svg
  src/assets/icons/person-default.svg
  src/assets/icons/person-filled.svg
  src/assets/icons/published-with-changes.svg
  src/assets/icons/radio-button-checked.svg
  src/assets/icons/radio-button-unchecked.svg
  src/assets/icons/search.svg
  src/assets/icons/store-default.svg
  src/assets/icons/store-filled.svg
  src/assets/icons/tune.svg
  src/assets/logo.svg
Labels: bug, chore

#22 #17 공통 컴포넌트 구현 (Chip, ProductItem, Grid-2columns, HorizontalLine,Gap)
  package.json
  pnpm-lock.yaml
  src/components/ArtistItem.tsx
  src/components/ArtistItem/LikeFollowers.tsx
  src/components/ArtistItem/Thumbnail.tsx
  src/components/ArtistItem/index.tsx
  src/components/CategoryTab/index.tsx
  src/components/CategoryTabElement.tsx
  src/components/CategoryTabs.tsx
  src/components/Chip/index.tsx
  src/components/FollowButton.tsx
  src/components/Gap/index.tsx
  src/components/Grid/index.tsx
  src/components/HorizontalLine/index.tsx
  src/components/LikeFollowers.tsx
  src/components/ProductItem/index.tsx
  src/components/Thumbnail.tsx
  src/components/Thumbnail/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: feature, chore

#24 헤더, 서치바 구현 #10
  package.json
  pnpm-lock.yaml
  src/assets/icons/cancel-filled-gray.svg
  src/components/Header/index.tsx
  src/components/IconButton/index.tsx
  src/components/SearchBar/index.tsx
  src/styles/reset.css
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: feature

#27 routes에서 중복되는 ProtectedRoute 정리 #20
  src/pages/ArtistDetails/index.tsx
  src/pages/Categories/index.tsx
  src/pages/Discover/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/My/index.tsx
  src/pages/MyFavorites/index.tsx
  src/pages/MyOrders/index.tsx
  src/pages/MySales/index.tsx
  src/pages/ProductDetails/index.tsx
  src/pages/ProductPosting/index.tsx
  src/pages/Search/index.tsx
  src/pages/SearchResults/index.tsx
  src/pages/Signup/index.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
Labels: refactor

#30 헤더 리팩토링 #28
  src/components/Header/index.tsx
Labels: refactor

#38 카테고리 페이지 UI 구현 #34
  src/apis/.gitkeep
  src/apis/data/categories.ts
  src/components/Grid/index.tsx
  src/components/IconButton/index.tsx
  src/components/SearchBar/index.tsx
  src/components/layout/Gap/index.tsx
  src/components/layout/Grid/index.tsx
  src/pages/Categories/components/CategoryItem/index.tsx
  src/pages/Categories/index.tsx
Labels: feature, design

#43 React does not recognize `isActive` prop on a DOM element 경고 제거 #42
  src/components/TabBar/Tab.tsx
Labels: bug

#40 공통 컴포넌트 구현 - TabBar #26
  src/assets/icons/chat-default.svg
  src/assets/icons/dashboard-default.svg
  src/assets/icons/home-default.svg
  src/assets/icons/menu-hamburger.svg
  src/assets/icons/person-default.svg
  src/components/IconButton/index.tsx
  src/components/TabBar/Tab.tsx
  src/components/TabBar/index.tsx
  src/components/layouts/BasicLayout/index.tsx
  src/pages/Chat/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: feature

#45 공통 컴포넌트 구현 - 푸터 #44
  src/assets/github.svg
  src/assets/notion.svg
  src/components/Footer/index.tsx
  src/pages/Home/index.tsx
  src/pages/My/index.tsx
Labels: feature

#48 TabList 모듈화 #47
  src/components/TabBar/index.tsx
  src/constants/TabList.tsx
Labels: refactor

#52 공통 컴포넌트 구현 - FAB
  src/assets/icons/add.svg
  src/assets/icons/arrow-upward.svg
  src/components/layouts/BasicLayout/index.tsx
  src/components/layouts/Footer/index.tsx
  src/components/layouts/Header/index.tsx
  src/pages/Home/index.tsx
  src/styles/reset.css
  src/types/.gitkeep
  src/types/index.ts
Labels: feature

#58 FAB svg 색깔 바꾸기, 레이아웃 수정 #55
  src/components/layouts/BasicLayout/index.tsx
  src/components/layouts/FAB/index.tsx
  src/components/layouts/Header/index.tsx
  src/components/layouts/TabBar/Tab.tsx
  src/components/layouts/TabBar/index.tsx
  src/pages/Home/index.tsx
Labels: bug

#59 메인(홈) 페이지 구현 #53
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/layouts/BasicLayout/index.tsx
  src/components/layouts/FAB/index.tsx
  src/components/layouts/TabBar/Tab.tsx
  src/components/layouts/TabBar/index.tsx
  src/constants/articleList.tsx
  src/constants/homeAdList.tsx
  src/constants/tabList.tsx
  src/pages/Home/AdBanner/index.tsx
  src/pages/Home/ArticleBanner/index.tsx
  src/pages/Home/index.tsx
  src/styles/reset.css
Labels: feature, refactor

#62 카테고리 페이지 UI 수정 #61
  src/components/layouts/NoHeaderLayout/index.tsx
  src/pages/Categories/index.tsx
Labels: feature, design

#64 7주차 코드 리뷰 피드백 #63
  package.json
  pnpm-lock.yaml
  src/components/common/SearchModal/RecentSearch.tsx
  src/components/layouts/SearchBar/index.tsx
  src/pages/SearchResults/index.tsx
Labels: feature, refactor

#66 7주차 코드 리뷰 피드백 - FAB 리팩토링 #65
  src/components/layouts/BasicLayout/index.tsx
  src/components/layouts/FAB/FABContainer.tsx
  src/components/layouts/FAB/index.tsx
  src/components/layouts/Header/index.tsx
  src/components/layouts/NoHeaderLayout/index.tsx
  src/pages/Home/index.tsx
Labels: bug, refactor

#67 공통 컴포넌트 구현 - CTA #41
  src/components/common/CTA/index.tsx
  src/pages/Signup/progresses/UserProgress.tsx
  src/pages/Signup/progresses/styles.ts
Labels: feature

#68 로그인 + 회원가입 페이지 UI #54
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/instance/index.ts
  src/apis/univ-cert/index.ts
  src/apis/univ-cert/useCertifyCode.ts
  src/apis/univ-cert/useCertifyEmail.ts
  src/apis/univ-cert/useCheckUniv.ts
  src/apis/univ-cert/useClearUser.ts
  src/assets/icons/arrow-back.svg
  src/assets/kakao-symbol.svg
  src/assets/logo.svg
  src/components/common/CTA/index.tsx
  src/components/common/IconButton/index.tsx
  src/components/common/form/Checkbox/index.tsx
  src/components/common/form/InputButton/index.tsx
  src/components/layouts/BasicLayout/index.tsx
  src/components/styles/HorizontalLine/index.tsx
  src/constants/home/articleList.tsx
  src/constants/home/homeAdList.tsx
  src/constants/login/backgroundImageList.tsx
  src/pages/Home/AdBanner/index.tsx
  src/pages/Home/ArticleBanner/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Signup/components/InputItem/index.tsx
  src/pages/Signup/components/MembershipClauses/CustomCheckbox.tsx
  src/pages/Signup/components/MembershipClauses/index.tsx
  src/pages/Signup/components/ProgressBar/index.tsx
  src/pages/Signup/index.tsx
  src/pages/Signup/progresses/DefaultProgress/index.tsx
  src/pages/Signup/progresses/SellerProgress/BusinessSeller/index.tsx
  src/pages/Signup/progresses/SellerProgress/StudentSeller/StudentSeller1.tsx
  src/pages/Signup/progresses/SellerProgress/StudentSeller/StudentSeller2.tsx
  src/pages/Signup/progresses/SellerProgress/index.tsx
  src/pages/Signup/progresses/UserProgress/index.tsx
  src/pages/Signup/progresses/styles.ts
  src/pages/Signup/progresses/utils.ts
  src/store/useStudentInfoStore.ts
  src/store/useUserInfoStore.ts
  src/utils/.gitkeep
  tsconfig.app.json
  vite.config.ts
Labels: feature
