Repository kakao-tech-campus-2nd-step3/Team9_FE, pull requests merged in 2024-09, with the labels that each got.

#3 프로젝트 세팅
  .gitignore
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: good first issue

#8 9조 FE 코드리뷰 1회차
  .gitignore
  README.md
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: documentation, chore, review

#11 chore 세팅 머지
  .eslintrc.js
  .prettierignore
  .prettierrc
  eslint.config.js
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: merge

#13 Feat/#9 컴포넌트 구현 4/9 완료
  .eslintrc.js
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/components/ArtistItem.tsx
  src/components/CategoryTabElement.tsx
  src/components/CategoryTabs.tsx
  src/components/FollowButton.tsx
  src/components/LikeFollowers.tsx
  src/components/Thumbnail.tsx
  src/index.css
  src/main.tsx
  src/styles/reset.css
  src/styles/variables.css
  vite.config.ts
Labels: feature

#15 절대 경로 설정, CSS 초기화 #5
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/.gitkeep
  src/assets/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/pages/ArtistDetails/index.tsx
  src/pages/Categories/index.tsx
  src/pages/Discover/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/My/index.tsx
  src/pages/MyFavorites/index.tsx
  src/pages/MyOrders/index.tsx
  src/pages/MySales/index.tsx
  src/pages/Mygallery/index.tsx
  src/pages/ProductDetails/index.tsx
  src/pages/ProductPosting/index.tsx
  src/pages/Search/index.tsx
  src/pages/SearchResults/index.tsx
  src/pages/Signup/index.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/types/.gitkeep
  src/utils/.gitkeep
  tsconfig.app.json
  vite.config.ts
Labels: feature, chore
