Repository kakao-tech-campus-2nd-step3/Team9_FE, pull requests merged in 2024-11, with the labels that each got.

#74 채팅 페이지 UI (채팅 목록) #73
  src/assets/icons/settings.svg
  src/components/common/IconButton/index.tsx
  src/pages/Chat/components/ChatItem/index.tsx
  src/pages/Chat/index.tsx
  src/utils/index.ts
Labels: feature

#75 서치 결과 페이지 남은 부분 구현 #57
  .eslintrc.js
  package.json
  src/components/common/ArtistItem/index.tsx
  src/components/common/FollowButton/index.tsx
  src/components/common/LikesAndFollowers/index.tsx
  src/components/common/ProductItem/index.tsx
  src/components/common/SearchModal/PopularSearch.tsx
  src/components/common/SearchModal/index.tsx
  src/components/common/Thumbnail/index.tsx
  src/components/layouts/Header/index.tsx
  src/components/layouts/SearchBar/index.tsx
  src/pages/Home/index.tsx
  src/pages/SearchResults/components/ArtWorkContents.tsx
  src/pages/SearchResults/components/ArtistContents.tsx
  src/pages/SearchResults/components/CategoryTabBar.tsx
  src/pages/SearchResults/components/Dropdown.tsx
  src/pages/SearchResults/components/MoreButton.tsx
  src/pages/SearchResults/components/SwiperFrame.tsx
  src/pages/SearchResults/index.tsx
Labels: feature

#79 Refactor/#78 week9
  src/apis/artists/usePostBusinessArtist.ts
  src/apis/artists/usePostStudentArtist.ts
  src/apis/instance/index.ts
  src/apis/nts-businessman/useVerifyBusiness.ts
  src/apis/univ-cert/useCertifyEmail.ts
  src/apis/univ-cert/useClearUser.ts
  src/apis/users/usePutUser.ts
  src/pages/Signup/index.tsx
  src/pages/Signup/progresses/ArtistProgress/StudentArtist/StudentArtist1.tsx
Labels: refactor

#80 9조 FE 코드리뷰 6회차 피드백 #76
  package.json
  src/components/common/CTA/index.tsx
  src/components/common/SearchModal/index.tsx
  src/components/layouts/Header/index.tsx
  src/pages/SearchResults/components/ArtWorkContents.tsx
  src/pages/SearchResults/components/ArtistContents.tsx
  src/pages/SearchResults/components/Dropdown.tsx
  src/pages/SearchResults/components/SwiperFrame.tsx
  src/pages/SearchResults/index.tsx
  src/pages/Signup/components/ProgressBar/index.tsx
  src/styles/z_index.ts
Labels: refactor

#84 (재) 채팅룸 페이지 구현 (API 빼고) #81
  src/assets/icons/send.svg
  src/components/common/IconButton/index.tsx
  src/components/common/ProfileImage/index.tsx
  src/components/layouts/SearchBar/index.tsx
  src/constants/tabList.tsx
  src/pages/chats/ChatList/components/ChatItem/index.tsx
  src/pages/chats/ChatList/index.tsx
  src/pages/chats/ChatRoom/components/ChatInput/index.tsx
  src/pages/chats/ChatRoom/components/Date/index.tsx
  src/pages/chats/ChatRoom/components/MessageItem/index.tsx
  src/pages/chats/ChatRoom/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/reset.css
Labels: feature

#86 마이 페이지 UI 구현 및 API 연결 #77
  src/apis/users/useDeleteFollow.ts
  src/apis/users/useGetFollow.ts
  src/apis/users/useGetUser.ts
  src/apis/users/usePostFollow.ts
  src/components/common/ArtistItem/index.tsx
  src/components/common/CategoryTabBar/CategoryTabElement.tsx
  src/components/common/CategoryTabBar/index.tsx
  src/components/layouts/FAB/FABContainer.tsx
  src/pages/My/components/ArtistProfileBox.tsx
  src/pages/My/components/MenuSection/ArtistMenuSection.tsx
  src/pages/My/components/MenuSection/MenuItem.tsx
  src/pages/My/components/MenuSection/UserMenuSection.tsx
  src/pages/My/components/UserProfileBox.tsx
  src/pages/My/index.tsx
  src/pages/MyFavorites/index.tsx
  src/pages/SearchResults/components/ArtistContents.tsx
  src/pages/SearchResults/components/CategoryTabBar.tsx
  src/pages/SearchResults/components/SwiperFrame.tsx
  src/pages/SearchResults/index.tsx
  src/types/index.ts
Labels: feature

#89 채팅 - UI 구현 및 WebSocket 연결 #71 #81
  package.json
  pnpm-lock.yaml
  src/apis/chats/index.ts
  src/assets/icons/send.svg
  src/components/common/IconButton/index.tsx
  src/components/common/ProfileImage/index.tsx
  src/components/layouts/SearchBar/index.tsx
  src/constants/tabList.tsx
  src/pages/chats/ChatList/components/ChatItem/index.tsx
  src/pages/chats/ChatList/index.tsx
  src/pages/chats/ChatRoom/components/ChatInput/index.tsx
  src/pages/chats/ChatRoom/components/Date/index.tsx
  src/pages/chats/ChatRoom/components/MessageItem/index.tsx
  src/pages/chats/ChatRoom/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/reset.css
  src/utils/index.ts
  vite.config.ts
Labels: feature

#90 둘러보기(discover) 페이지 구현 #82
  src/apis/products/useGetFeed.ts
  src/components/layouts/SearchBar/index.tsx
  src/pages/Discover/index.tsx
Labels: feature

#92 둘러보기(discover) 페이지 구현 #82 #90
  src/apis/products/useGetFeed.ts
  src/components/layouts/SearchBar/index.tsx
  src/pages/Discover/index.tsx
Labels: feature

#96 Weekly10 에러 픽스 #95
  src/apis/products/useGetFeed.ts
Labels: bug

#100 weekly10 리팩토링 #97
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/artists/usePostBusinessArtist.ts
  src/apis/artists/usePostStudentArtist.ts
  src/apis/fetchInstance.ts
  src/apis/instance/index.ts
  src/apis/nts-businessman/useVerifyBusiness.ts
  src/apis/products/useGetFeed.ts
  src/apis/queryClient.ts
  src/apis/queryKeys.ts
  src/apis/univ-cert/useCertifyCode.ts
  src/apis/univ-cert/useCertifyEmail.ts
  src/apis/univ-cert/useCheckUniv.ts
  src/apis/univ-cert/useClearUser.ts
  src/apis/users/useDeleteFollow.ts
  src/apis/users/useGetFollow.ts
  src/apis/users/useGetUser.ts
  src/apis/users/usePostFollow.ts
  src/apis/users/usePutUser.ts
  src/components/common/CTA/index.tsx
  src/components/common/SearchModal/index.tsx
  src/components/layouts/FAB/FABContainer.tsx
  src/components/layouts/Header/index.tsx
  src/components/layouts/SearchBar/index.tsx
  src/components/layouts/TabBar/index.tsx
  src/pages/Discover/index.tsx
  src/pages/My/index.tsx
  src/pages/MyFavorites/index.tsx
  src/pages/SearchResults/components/ArtistContents.tsx
  src/pages/SearchResults/components/Dropdown.tsx
  src/pages/SearchResults/components/SwiperFrame.tsx
  src/pages/SearchResults/index.tsx
  src/pages/Signup/components/ProgressBar/index.tsx
  src/styles/zIndex.ts
Labels: refactor

#101 10주차 코드 리뷰 피드백 #99
  src/apis/instance/index.ts
  src/apis/users/useGetArtist.ts
  src/apis/users/useGetUser.ts
  src/pages/My/components/UserProfileBox.tsx
  src/pages/My/index.tsx
Labels: feature, refactor

#102 추가 feedback 반영 #99
  src/apis/users/useDeleteFollow.ts
  src/apis/users/useGetArtist.ts
  src/apis/users/useGetUser.ts
  src/apis/users/usePostFollow.ts
Labels: refactor

#104 constants, styles 폴더 정리 #103
  src/components/common/CTA/index.tsx
  src/components/common/FakeSearchBar/index.tsx
  src/components/common/SearchModal/index.tsx
  src/components/layouts/FAB/FABContainer.tsx
  src/components/layouts/Header/index.tsx
  src/components/layouts/SearchBar/index.tsx
  src/components/layouts/TabBar/index.tsx
  src/constants/home.ts
  src/constants/home/articleList.tsx
  src/constants/login.ts
  src/constants/tabList.tsx
  src/pages/Discover/index.tsx
  src/pages/Home/components/AdBanner/index.tsx
  src/pages/Home/components/ArticleBanner/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/SearchResults/components/Dropdown.tsx
  src/pages/SearchResults/index.tsx
  src/pages/Signup/components/ProgressBar/index.tsx
  src/pages/Signup/index.tsx
  src/pages/chats/ChatList/index.tsx
  src/pages/chats/ChatRoom/index.tsx
  src/styles/constants.ts
  src/styles/zIndex.ts
Labels: refactor

#106 Discover 에러바운더리 오류 픽스 #105
  src/pages/Discover/index.tsx
Labels: bug

#111 채팅 - DTO 맞추고 기능 구현 #93
  package.json
  pnpm-lock.yaml
  src/apis/chats/index.ts
  src/apis/chats/useGetChatRoom.ts
  src/apis/chats/usePostChatRoom.ts
  src/apis/queryKeys.ts
  src/assets/icons/image.svg
  src/pages/ProductDetails/index.tsx
  src/pages/chats/ChatRoom/components/ChatInput/index.tsx
  src/pages/chats/ChatRoom/components/Date/index.tsx
  src/pages/chats/ChatRoom/components/MessageItem/index.tsx
  src/pages/chats/ChatRoom/components/MessageList/index.tsx
  src/pages/chats/ChatRoom/index.tsx
  src/routes/index.tsx
  src/types/chats.ts
  src/utils/index.ts
  src/utils/queryParams.ts
Labels: feature

#113 로그인, 유저 모드 api 연결 #94
  src/apis/instance/index.ts
  src/apis/queryKeys.ts
  src/apis/users/getUserMode.ts
  src/pages/Home/index.tsx
  src/pages/Login/components/KakaoLoginButton/index.tsx
  src/pages/Login/index.tsx
  src/pages/Signup/index.tsx
  src/utils/queryParams.ts
Labels: feature

#116 로그인하면 유저 모드(타입) 세팅 #115
  src/App.tsx
  src/apis/users/getUserMode.ts
  src/components/layouts/FAB/FABContainer.tsx
  src/components/layouts/Header/index.tsx
  src/pages/Home/index.tsx
  src/pages/My/index.tsx
  src/pages/Signup/index.tsx
  src/pages/Signup/progresses/DefaultProgress/index.tsx
  src/store/useModeStore.ts
  src/types/index.ts
Labels: feature, refactor

#117 검색 api, 상품 api 연결 #108
  src/apis/artists/useGetProfile.ts
  src/apis/data/searchArtist.ts
  src/apis/data/searchWork.ts
  src/apis/products/useGetDetail.ts
  src/apis/queryKeys.ts
  src/apis/search/useSearchArtists.tsx
  src/apis/search/useSearchProducts.tsx
  src/apis/users/useDeleteLikes.ts
  src/apis/users/usePostLikes.ts
  src/components/common/ArtistItem/index.tsx
  src/components/common/ProductItem/index.tsx
  src/components/common/Thumbnail/index.tsx
  src/pages/ArtistDetails/index.tsx
  src/pages/ProductDetails/index.tsx
  src/pages/SearchResults/components/ArtWorkContents.tsx
  src/pages/SearchResults/components/ArtistContents.tsx
  src/pages/SearchResults/components/HorizontalFrame.tsx
  src/pages/SearchResults/index.tsx
  src/types/index.ts
Labels: feature

#124 모바일 크로스 브라우징, 모바일 화면 CSS 수정 #123
  index.html
  src/components/common/Chip/index.tsx
  src/components/common/form/Checkbox/index.tsx
  src/components/common/form/InputButton/index.tsx
  src/components/layouts/SearchBar/index.tsx
  src/pages/Signup/components/InputItem/index.tsx
  src/pages/Signup/progresses/ArtistProgress/index.tsx
  src/pages/Signup/progresses/DefaultProgress/index.tsx
  src/pages/Signup/progresses/styles.ts
  src/styles/reset.css
Labels: bug, design

#129 검색 리팩토링, API 관련 버그 수정 #126 #127
  package.json
  pnpm-lock.yaml
  src/apis/fetchInstance.ts
  src/apis/products/useGetFeed.ts
  src/assets/icons/cancel-filled-gray.svg
  src/assets/icons/cancel-filled.svg
  src/components/common/CategoryTabBar/index.tsx
  src/components/common/Chip/index.tsx
  src/components/common/FakeSearchBar/index.tsx
  src/components/common/PopularSearchItem/index.tsx
  src/components/common/ProfileImage/index.tsx
  src/components/common/SearchModal/Ad.tsx
  src/components/common/SearchModal/PopularSearch.tsx
  src/components/common/SearchModal/RecentSearch.tsx
  src/components/common/SearchModal/SearchAd.tsx
  src/components/common/SearchModal/index.tsx
  src/components/common/SearchModal/styles.ts
  src/components/layouts/Header/index.tsx
  src/components/layouts/SearchBar/index.tsx
  src/constants/categories.ts
  src/constants/search.ts
  src/pages/Categories/components/CategoryItem/index.tsx
  src/pages/Categories/components/CurationItem/index.tsx
  src/pages/Categories/index.tsx
  src/pages/Discover/index.tsx
  src/pages/Home/index.tsx
  src/pages/SearchResults/index.tsx
  src/store/useSearchModalStore.ts
  src/styles/globalStyles.ts
Labels: bug, feature, refactor
